import type { AppState } from './types'

export const PURPOSE_OPTIONS = [
  'Rent / eviction risk',
  'Medical bill',
  'Utilities',
  'Transportation repair',
  'Childcare gap',
  'Short-term income shock',
  'Other emergency',
]

export const DOC_OPTIONS = [
  'Pay stub',
  'Lease or rent notice',
  'Medical invoice',
  'Utility statement',
  'Bank statement',
  'Employer letter',
]

export const US_STATES = [
  'AL',
  'AK',
  'AZ',
  'AR',
  'CA',
  'CO',
  'CT',
  'DE',
  'FL',
  'GA',
  'HI',
  'ID',
  'IL',
  'IN',
  'IA',
  'KS',
  'KY',
  'LA',
  'ME',
  'MD',
  'MA',
  'MI',
  'MN',
  'MS',
  'MO',
  'MT',
  'NE',
  'NV',
  'NH',
  'NJ',
  'NM',
  'NY',
  'NC',
  'ND',
  'OH',
  'OK',
  'OR',
  'PA',
  'RI',
  'SC',
  'SD',
  'TN',
  'TX',
  'UT',
  'VT',
  'VA',
  'WA',
  'WV',
  'WI',
  'WY',
]

export const createDefaultState = (): AppState => {
  const now = new Date().toISOString()

  return {
    applications: [
      {
        id: 'app-1001',
        name: 'Tanya R.',
        state: 'TX',
        amount: 850,
        purpose: 'Rent / eviction risk',
        monthlyIncome: 1900,
        docs: ['Pay stub', 'Lease or rent notice'],
        aiScore: 78,
        aiDecision: 'review',
        status: 'submitted',
        createdAt: now,
      },
      {
        id: 'app-1002',
        name: 'Carlos M.',
        state: 'TX',
        amount: 900,
        purpose: 'Transportation repair',
        monthlyIncome: 2400,
        docs: ['Pay stub', 'Bank statement'],
        aiScore: 84,
        aiDecision: 'approve',
        status: 'approved',
        createdAt: now,
      },
    ],
    loans: [
      {
        id: 'loan-2001',
        applicationId: 'app-1002',
        borrowerName: 'Carlos M.',
        principal: 900,
        balance: 750,
        interestRate: 2.4,
        termMonths: 12,
        monthlyPayment: 78,
        status: 'active',
      },
    ],
    lender: {
      name: 'Sample Lender',
      since: now,
      monthlyContribution: 10,
      totalDeposits: 120,
      lendingAllocation: 70,
      yieldAllocation: 30,
      maxExposure: 100,
    },
    proposals: [
      {
        id: 'prop-1',
        title: 'Raise borrower cap to $12,000',
        description:
          'Proposal to evaluate whether borrower caps can expand without increasing harm.',
        status: 'open',
        votesFor: 128,
        votesAgainst: 62,
      },
      {
        id: 'prop-2',
        title: 'Increase cooling-off period to 90 days',
        description:
          'Reduce repeat borrowing risk while protecting access during emergencies.',
        status: 'open',
        votesFor: 204,
        votesAgainst: 41,
      },
    ],
    audit: [
      {
        id: 'audit-1',
        at: now,
        actor: 'System',
        action: 'Initialized demo data',
        detail: 'Loaded sample borrower and lender state.',
      },
    ],
    platformPaused: false,
  }
}
